### ISSUE TITLE
Cupon not applied

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#266]
![Screen Shot 2021-03-25 at 9 23 24 AM](https://user-images.githubusercontent.com/411114/112476624-6548f380-8d72-11eb-987f-76ed7f152207.png)

**Comment by acidbiscuit** [comment]
@davidgatti Is there a fixed discount or a way to get coupon discount percentage?

**Comment by davidgatti** [comment]
Yes once you get a positive response you can make a DDB Get request with:

- `pk`: id of the cupon
- `sk`: "cupon"

And this is what you get back.

```
{
  "coupon_id": "hello",
  "duration": "forever",
  "duration_in_months": "1",
  "max_redemptions": "100",
  "percent_off": "20",
  "pk": "hello",
  "sk": "cupon",
  "ts_created": "2021-03-27T06:01:00.603Z"
}
```

**Comment by acidbiscuit** [comment]
@davidgatti 

I am unable to get coupon details with settings above. Here is an error message:

```
User: arn:aws:sts::257214433955:assumed-role/marketing_merchant_form_cognito_identitypool_authenticated/CognitoIdentityCredentials is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:257214433955:table/money
```

We are making a request to `money` table, right?

**Comment by davidgatti** [comment]
OK, looking in to this

**Comment by acidbiscuit** [comment]
@davidgatti I am still facing the issue.

**Comment by davidgatti** [comment]
I know, becasue I did not look in to it yet :D when I'll do I will let you know here.

**Comment by acidbiscuit** [comment]
@davidgatti Check coupon method now works. Thank you.

When trying to apply the coupon I am facing an error:

```
{
   "__type":"com.amazon.coral.service#AccessDeniedException",
   "Message":"User: arn:aws:sts::257214433955:assumed-role/marketing_merchant_form_cognito_identitypool_authenticated/CognitoIdentityCredentials is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:257214433955:table/money"
}
```

**Comment by davidgatti** [comment]
@acidbiscuit I did fix the policy, and not it should work. But I ddi remove the subscription check lambda, since the CloudFormation had it remove - I can't remember why I did that, but I will add it back tomorrow. so if something esle broke it is because of me.

**Comment by acidbiscuit** [comment]
@davidgatti The issue persists.

Request:
```
{
   "TableName":"money",
   "Key":{
      "pk":{
         "S":"g5mSqxS5"
      },
      "sk":{
         "S":"cupon"
      }
   }
}
```

Response:
```
{
   "__type":"com.amazon.coral.service#AccessDeniedException",
   "Message":"User: arn:aws:sts::257214433955:assumed-role/marketing_merchant_form_cognito_identitypool_authenticated/CognitoIdentityCredentials is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:257214433955:table/money"
}
```

**Comment by davidgatti** [comment]
When I test on my side, it works. I get no error. Maybe you have an old session, log out and log back in. And from the response that. Isend you back I'm not sending you the % of the cupon, so I have to update the code to send you that info back.

**Comment by davidgatti** [comment]
@acidbiscuit ok, I did update the lambda, now the payload looks like this:

```
{
    "valid": false,
    "percent_off": 22
}
```

If the valid key is true, then display the %, otherwise don't.

**Comment by davidgatti** [comment]
ps. how do we add the discount to the account, you pass it to the Stripe widget?

**Comment by acidbiscuit** [comment]
> ps. how do we add the discount to the account, you pass it to the Stripe widget?

@davidgatti  Coupon ID is now being sent as `coupon` field when we create a record in DB for payment details.

**Comment by davidgatti** [comment]
man, I need to write a documentation of what was done and how it works :)
