### ISSUE TITLE
Detect the new version of the page

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#297]
In VuePress there is this cool feature where they are able to detect when there is a new version of the page, without any fancy back-end or any extra work from the infrastructure itself. 

I'd like to have a similar solution in the dashboard.

**Comment by acidbiscuit** [comment]
@davidgatti In Nuxt.js we download new content by default without any user actions. To add such notification, we would have to disable automatic content update and add a button for users to update. This means that application will run cache first and may not be necessarily work as well for interactive dashboards as it does not documentation.

Should we disable automatic updates?

**Comment by davidgatti** [comment]
I had no idea this is how it worked. How dose the setup that we have right now, know when to pull new data? Dose it always reaches the source, or dose it caches locally and pull new data when needed. How dose this mechanism work right now?

**Comment by acidbiscuit** [comment]
@davidgatti Current setup is achieved through [Service worker API](https://developers.google.com/web/fundamentals/primers/service-workers) managed by [Workbox](https://developers.google.com/web/tools/workbox) as part of [Nuxt.js PWA module](https://pwa.nuxtjs.org/).

During every build there is a separate service worker file generated. Service worker is a script that runs in the background and becomes a middleman between the page and network. Upon the first visit browser loads the page and registers service worker in the background. Service worker takes control of the page and creates cache for all the assets to provide offline experience. From this moment every asset request made by the page goes through the Service Worker which decides to provide cached asset from disk cache, service worker cache or make a network request. On next visit the page is served from the service worker, but browser makes another request to check service worker version. If service worker version is different (aka project has been rebuilt), it will update local caches for all the files that have been updated using it's own "revision" mechanism.

**Comment by davidgatti** [comment]
ooo fancy. very cool had no idea. thank you for the detailed explanation.
