### ISSUE TITLE
Avatar is not updated everywhere

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#298]
When I upload a new image, the image in the drop down menu is not replaced, a refresh of the page will fix that, but I would not like to have to do that if possible.

![Screen Shot 2021-06-15 at 7 06 54 AM](https://user-images.githubusercontent.com/411114/122000003-6f492400-cdae-11eb-8d58-f7000023b2b5.png)

**Comment by acidbiscuit** [comment]
@davidgatti I am not able to reproduce the issue locally. Is there a live link I can test?

**Comment by davidgatti** [comment]
SO you are saying that when you replace the image, the one from the menu will also be replaced?

**Comment by acidbiscuit** [comment]
@davidgatti That is correct

**Comment by davidgatti** [comment]
hmm strange, ok, in this case we can skip this one.
