### ISSUE TITLE
New approach for multi core build

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#299]
We updated in the past the build script to take advantage of multicore, and we did it by sending different categories to different cores. The problem is, that some categories have vastly different item count. And turns out that the time benefit gose out the window, when one category is left processing on just one core.

We need to update the code, to not organize the work by category, but make a big list of all the individual items regardless of category, and split that in to the amount of corse that a CPU has - 1, why -1? to allow the OS to have one core for itself to it can still perform all normal functions.

**Comment by acidbiscuit** [comment]
@davidgatti Is this issue related to AVC website project?

**Comment by davidgatti** [comment]
lol :D wrong place ;)

**Comment by davidgatti** [comment]
And yes, this is for AVC, sorry

**Comment by davidgatti** [comment]
Moved here: aws-videos-catalog/avc_website/issues/233
