### ISSUE TITLE
New way to display the invoice

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#300]
I think I did figure out the invoice situation, Stripe is not making it easy. So now there is a new entry in the DDB as you can see bellow:

![Screen Shot 2021-06-21 at 8 31 23 AM](https://user-images.githubusercontent.com/411114/122716901-26d8ad00-d26b-11eb-81eb-8d6b1968b039.png)

And inside it, there is this data:

```
{
  "amount_due": 100,
  "amount_paid": 0,
  "amount_remaining": 100,
  "created": "2021-06-20T04:50:19Z",
  "invoice_pdf": null,
  "pk": "us-east-1:ec69d0d8-40da-4a66-bd3c-48c558741ccb",
  "sk": "invoice#summary#2021#06#in_1J4IbvG1wg42NuVovJ0adK2Q",
  "type": "invoice.created"
}
```

That we for now want to display as the main information for the invoice. Don't display the PK and SK, but display the rest as is, and then we will take it from there.

You still have the invoice count summary:

```
{
  "count": 1,
  "pk": "us-east-1:ec69d0d8-40da-4a66-bd3c-48c558741ccb",
  "sk": "stats#invoice#summary"
}
```

To know how many invoice will be present.

I have more data that can be displayed as the full history of the invoice, but we will add it once we have this basic info first, and then I will think how to display all the historically data of the state of the invoice, since there is quite the amount of data, but as of now I'm not sure sure what to keep and what to discard.

**Comment by acidbiscuit** [comment]
@davidgatti I've added an PR with new information for invoices.

 Btw, DB request to `stats#invoice#summary` doesn't seem to allow to filter by date (e.g. `stats#invoice#summary#2021`). We need to filter by year to make pagination work. Is there a way to use it with year filter?

**Comment by davidgatti** [comment]
I will have to update this in the back end, will work on it.
