### ISSUE TITLE
Question: do you invoke this lambda in the project?

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#304]
Something similar to this? `dr_webpage_dashboard_app_subscription_check` the name might be different but you get idea.

**Comment by acidbiscuit** [comment]
@davidgatti Yes. It is called on the dashboard when Save button is clicked and currently not working. It was added for testing purposes.

**Comment by davidgatti** [comment]
ok, cool. can you paste the URL to the line where you invoke that lambda - especially the name that you use.

**Comment by acidbiscuit** [comment]
@davidgatti  https://github.com/0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard/blob/master/store/payment.js#L137
