### ISSUE TITLE
Invoice column view

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#307]
- Red: remove column for pdf download, it gets confusing when you want to click for details, the row needs to just have one action.
- Blue: display the currency that you get from the database
- Green: the status seams wrong, is this what you get from the DB, and just displaying as is? Or you miss-configured something?
 
![Screen Shot 2021-08-12 at 7 29 36 AM](https://user-images.githubusercontent.com/411114/129143785-19eaa606-d3aa-494c-86a7-06330d85f094.png)

**Comment by acidbiscuit** [comment]
@davidgatti I've made changes to invoices list.

I had custom formatting for invoice type, which now removed to reflect they type from the DB.  
Also there is no currency available for invoices list response.

**Comment by davidgatti** [comment]
Add currency to the DDB.
