### ISSUE TITLE
Same margins?

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#313]
Can we have the same margins for this, without to much hassle for the standard that was created?

![Screen Shot 2021-08-21 at 5 55 47 PM](https://user-images.githubusercontent.com/411114/130327850-15dbf577-a6df-43d3-997e-cea1b829fd6b.png)

**Comment by acidbiscuit** [comment]
@davidgatti Yes, sure.

**Comment by davidgatti** [comment]
Then lets do it :)
