### ISSUE TITLE
Small things

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_webpage_dashboard#317]
Few small changes...

## Footer

`Est.2016, Copr.0x4447™ LLC.` to this `Est. 2016, Copr. 0x4447™ LLC.` added two spaces.

## Display Event ID

New Key named `event_id`

![Screen Shot 2021-08-27 at 7 30 30 AM copy](https://user-images.githubusercontent.com/411114/131165193-5f900150-326f-4177-a1a9-5adcaf03b3d0.png)

## Remove time created

![Screen Shot 2021-08-27 at 7 30 30 AM copy](https://user-images.githubusercontent.com/411114/131165310-3732a1e3-380f-4dbd-b314-d18bd20f90e4.png)

## Price wont fit

![Screen Shot 2021-08-27 at 7 30 30 AM copy](https://user-images.githubusercontent.com/411114/131165569-b7c7ac6d-5f9a-44fe-aa9e-dd4a377aa80f.png)

## Remove arrow
 
![Screen Shot 2021-08-27 at 7 32 00 AM copy](https://user-images.githubusercontent.com/411114/131165802-60261582-785d-43e3-970f-c7749a60817c.png)

## Tab refresh content

![Screen Shot 2021-08-27 at 7 32 00 AM copy](https://user-images.githubusercontent.com/411114/131166036-896b9b8e-02dc-4a58-9fd5-cfcee7883901.png)

## Show currency 

Now you can display it, in the DDB object you should now you have the `currency` key

![Screen Shot 2021-08-27 at 7 32 00 AM copy](https://user-images.githubusercontent.com/411114/131166178-758d2cce-989d-4d78-b0ea-73c582172199.png)

## Negative numbers

![Screen Shot 2021-08-27 at 7 32 00 AM copy](https://user-images.githubusercontent.com/411114/131166703-36483b00-1e5d-4d77-aefa-09282891f662.png)

**Comment by acidbiscuit** [comment]
@davidgatti 

Tab refresh content is not a good solution for the problem. It is a default browser behavior to not trigger navigation when link URL is current page URL. If there is a need to have a refresh functionality and browser page refresh does not suffice, it should be added a separate button on the page.
